server {
    listen 80;
    root /usr/share/nginx/html;
    index pages/viewer/viewer.html;

    # Redirigir / directamente al viewer
    location = / {
        return 302 /pages/viewer/viewer.html;
    }

    # Servir ficheros estáticos normalmente
    location / {
        try_files $uri $uri/ =404;
    }
}
