"""add_db_merkle_consistent_to_verifications

Revision ID: b4d8ad4df163
Revises: 01f790990938
Create Date: 2026-03-03 16:32:26.233211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d8ad4df163'
down_revision: Union[str, None] = '01f790990938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
